:doctype: book
:toc: left
:toclevels: 4
:sectnums:
:reproducible:
:sail-doc: {docdir}/tara.json
:document-title-suffix:

include::sailcomment:document_subtitle[type=anchor,indent=0]

ifdef::backend-pdf[]
:document-title-suffix: : {document-subtitle}
endif::[]

include::sailcomment:document_title[type=anchor,indent=0]

ifndef::backend-pdf[]
[.lead]
{document-subtitle}
endif::[]

[preface]
== Preface

include::sailcomment:document_introduction[type=anchor,indent=0]

include::sailcomment:machine[type=anchor,indent=0]

include::sailcomment:section_machine[type=anchor,indent=0]

include::sailcomment:types[type=anchor,indent=0]

sail::word[type=type]
sail::byte[type=type]
sail::regidx[type=type]
sail::address[type=type]
sail::regfile[type=type]
sail::memory[type=type]

include::sailcomment:GPR[type=register,indent=0]
sail::GPR[type=register]

include::sailcomment:PC[type=register,indent=0]
sail::PC[type=register]

include::sailcomment:MEM[type=register,indent=0]
sail::MEM[type=register]

include::sailcomment:HALTED[type=register,indent=0]
sail::HALTED[type=register]

include::sailcomment:KEYS[type=register,indent=0]
sail::KEYS[type=register]

include::sailcomment:nextPC[type=register,indent=0]
sail::nextPC[type=register]

include::sailcomment:rX[type=function,indent=0]
sail::rX[type=function]

include::sailcomment:wX[type=function,indent=0]
sail::wX[type=function]

include::sailcomment:lr[type=let,indent=0]
sail::lr[type=let]

include::sailcomment:sp[type=let,indent=0]
sail::sp[type=let]

include::sailcomment:pc_mask[type=function,indent=0]
sail::pc_mask[type=function]

include::sailcomment:input_port[type=let,indent=0]
sail::input_port[type=let]

include::sailcomment:read_byte[type=function,indent=0]
sail::read_byte[type=function]

include::sailcomment:write_byte[type=function,indent=0]
sail::write_byte[type=function]

include::sailcomment:read_word[type=function,indent=0]
sail::read_word[type=function]

include::sailcomment:write_word[type=function,indent=0]
sail::write_word[type=function]

include::sailcomment:pixel[type=val,indent=0]
sail::pixel[type=function]

include::sailcomment:section_instruction_set[type=anchor,indent=0]

include::sailcomment:encoding[type=anchor,indent=0]

include::sailcomment:section_instruction_formats[type=anchor,indent=0]

include::formats.adoc[]

include::sailcomment:section_opcodes[type=anchor,indent=0]

include::opcodes.adoc[]

include::sailcomment:decode[grep=None\(,indent=0]
sail::decode[grep=None\(]

include::sailcomment:operands[type=anchor,indent=0]

sail::instruction[type=type]

include::sailcomment:encode[type=val,indent=0]
sail::encode[type=val]

include::sailcomment:decode[type=val,indent=0]
sail::decode[type=val]

include::sailcomment:execute[type=val,indent=0]
sail::execute[type=val]

include::sailcomment:section_data_movement[type=anchor,indent=0]

include::sailcomment:data_movement[type=anchor,indent=0]

[#insn-NOP%breakable]
==== `NOP`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="NOP()",indent=0]
sail::encode[clause="NOP()"]
sail::decode[grep=Some\(NOP\(]
sail::execute[clause="NOP()"]
sail::assembly_syntax[type=mapping,left-clause="NOP()"]

--

[#insn-HLT%breakable]
==== `HLT`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="HLT()",indent=0]
sail::encode[clause="HLT()"]
sail::decode[grep=Some\(HLT\(]
sail::execute[clause="HLT()"]
sail::assembly_syntax[type=mapping,left-clause="HLT()"]

--

[#insn-MOV%breakable]
==== `MOV`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="MOV(_, _)",indent=0]
sail::encode[clause="MOV(_, _)"]
sail::decode[grep=Some\(MOV\(]
sail::execute[clause="MOV(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="MOV(_, _)"]

--

[#insn-LIL%breakable]
==== `LIL`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="LIL(_, _)",indent=0]
sail::encode[clause="LIL(_, _)"]
sail::decode[grep=Some\(LIL\(]
sail::execute[clause="LIL(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="LIL(_, _)"]

--

[#insn-LIH%breakable]
==== `LIH`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="LIH(_, _)",indent=0]
sail::encode[clause="LIH(_, _)"]
sail::decode[grep=Some\(LIH\(]
sail::execute[clause="LIH(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="LIH(_, _)"]

--

include::sailcomment:section_memory[type=anchor,indent=0]

include::sailcomment:memory[type=anchor,indent=0]

[#insn-LDW%breakable]
==== `LDW`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="LDW(_, _, _)",indent=0]
sail::encode[clause="LDW(_, _, _)"]
sail::decode[grep=Some\(LDW\(]
sail::execute[clause="LDW(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="LDW(_, _, _)"]

--

[#insn-STW%breakable]
==== `STW`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="STW(_, _, _)",indent=0]
sail::encode[clause="STW(_, _, _)"]
sail::decode[grep=Some\(STW\(]
sail::execute[clause="STW(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="STW(_, _, _)"]

--

[#insn-LDB%breakable]
==== `LDB`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="LDB(_, _, _)",indent=0]
sail::encode[clause="LDB(_, _, _)"]
sail::decode[grep=Some\(LDB\(]
sail::execute[clause="LDB(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="LDB(_, _, _)"]

--

[#insn-STB%breakable]
==== `STB`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="STB(_, _, _)",indent=0]
sail::encode[clause="STB(_, _, _)"]
sail::decode[grep=Some\(STB\(]
sail::execute[clause="STB(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="STB(_, _, _)"]

--

include::sailcomment:section_arithmetic[type=anchor,indent=0]

include::sailcomment:arithmetic[type=anchor,indent=0]

[#insn-ADD%breakable]
==== `ADD`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="ADD(_, _, _)",indent=0]
sail::encode[clause="ADD(_, _, _)"]
sail::decode[grep=Some\(ADD\(]
sail::execute[clause="ADD(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="ADD(_, _, _)"]

--

[#insn-SUB%breakable]
==== `SUB`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="SUB(_, _, _)",indent=0]
sail::encode[clause="SUB(_, _, _)"]
sail::decode[grep=Some\(SUB\(]
sail::execute[clause="SUB(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="SUB(_, _, _)"]

--

[#insn-ADDI%breakable]
==== `ADDI`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="ADDI(_, _)",indent=0]
sail::encode[clause="ADDI(_, _)"]
sail::decode[grep=Some\(ADDI\(]
sail::execute[clause="ADDI(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="ADDI(_, _)"]

--

[#insn-MUL%breakable]
==== `MUL`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="MUL(_, _, _)",indent=0]
sail::encode[clause="MUL(_, _, _)"]
sail::decode[grep=Some\(MUL\(]
sail::execute[clause="MUL(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="MUL(_, _, _)"]

--

include::sailcomment:section_logic[type=anchor,indent=0]

include::sailcomment:logic[type=anchor,indent=0]

[#insn-AND%breakable]
==== `AND`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="AND(_, _, _)",indent=0]
sail::encode[clause="AND(_, _, _)"]
sail::decode[grep=Some\(AND\(]
sail::execute[clause="AND(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="AND(_, _, _)"]

--

[#insn-OR%breakable]
==== `OR`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="OR(_, _, _)",indent=0]
sail::encode[clause="OR(_, _, _)"]
sail::decode[grep=Some\(OR\(]
sail::execute[clause="OR(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="OR(_, _, _)"]

--

[#insn-XOR%breakable]
==== `XOR`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="XOR(_, _, _)",indent=0]
sail::encode[clause="XOR(_, _, _)"]
sail::decode[grep=Some\(XOR\(]
sail::execute[clause="XOR(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="XOR(_, _, _)"]

--

[#insn-NOT%breakable]
==== `NOT`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="NOT(_, _)",indent=0]
sail::encode[clause="NOT(_, _)"]
sail::decode[grep=Some\(NOT\(]
sail::execute[clause="NOT(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="NOT(_, _)"]

--

include::sailcomment:section_shifts[type=anchor,indent=0]

include::sailcomment:shifts[type=anchor,indent=0]

[#insn-SHL%breakable]
==== `SHL`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="SHL(_, _)",indent=0]
sail::encode[clause="SHL(_, _)"]
sail::decode[grep=Some\(SHL\(]
sail::execute[clause="SHL(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="SHL(_, _)"]

--

[#insn-SHR%breakable]
==== `SHR`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="SHR(_, _)",indent=0]
sail::encode[clause="SHR(_, _)"]
sail::decode[grep=Some\(SHR\(]
sail::execute[clause="SHR(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="SHR(_, _)"]

--

include::sailcomment:section_comparison[type=anchor,indent=0]

include::sailcomment:comparison[type=anchor,indent=0]

[#insn-SLT%breakable]
==== `SLT`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="SLT(_, _, _)",indent=0]
sail::encode[clause="SLT(_, _, _)"]
sail::decode[grep=Some\(SLT\(]
sail::execute[clause="SLT(_, _, _)"]
sail::assembly_syntax[type=mapping,left-clause="SLT(_, _, _)"]

--

include::sailcomment:section_control_flow[type=anchor,indent=0]

include::sailcomment:control_flow[type=anchor,indent=0]

[#insn-BZ%breakable]
==== `BZ`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="BZ(_, _)",indent=0]
sail::encode[clause="BZ(_, _)"]
sail::decode[grep=Some\(BZ\(]
sail::execute[clause="BZ(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="BZ(_, _)"]

--

[#insn-BN%breakable]
==== `BN`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="BN(_, _)",indent=0]
sail::encode[clause="BN(_, _)"]
sail::decode[grep=Some\(BN\(]
sail::execute[clause="BN(_, _)"]
sail::assembly_syntax[type=mapping,left-clause="BN(_, _)"]

--

[#insn-JMP%breakable]
==== `JMP`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="JMP(_)",indent=0]
sail::encode[clause="JMP(_)"]
sail::decode[grep=Some\(JMP\(]
sail::execute[clause="JMP(_)"]
sail::assembly_syntax[type=mapping,left-clause="JMP(_)"]

--

[#insn-CALL%breakable]
==== `CALL`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="CALL(_)",indent=0]
sail::encode[clause="CALL(_)"]
sail::decode[grep=Some\(CALL\(]
sail::execute[clause="CALL(_)"]
sail::assembly_syntax[type=mapping,left-clause="CALL(_)"]

--

[#insn-RET%breakable]
==== `RET`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="RET()",indent=0]
sail::encode[clause="RET()"]
sail::decode[grep=Some\(RET\(]
sail::execute[clause="RET()"]
sail::assembly_syntax[type=mapping,left-clause="RET()"]

--

include::sailcomment:section_stack[type=anchor,indent=0]

include::sailcomment:stack[type=anchor,indent=0]

[#insn-PUSH%breakable]
==== `PUSH`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="PUSH(_)",indent=0]
sail::encode[clause="PUSH(_)"]
sail::decode[grep=Some\(PUSH\(]
sail::execute[clause="PUSH(_)"]
sail::assembly_syntax[type=mapping,left-clause="PUSH(_)"]

--

[#insn-POP%breakable]
==== `POP`

[.instruction%unbreakable]
--

include::sailcomment:execute[clause="POP(_)",indent=0]
sail::encode[clause="POP(_)"]
sail::decode[grep=Some\(POP\(]
sail::execute[clause="POP(_)"]
sail::assembly_syntax[type=mapping,left-clause="POP(_)"]

--

include::sailcomment:section_execution[type=anchor,indent=0]

include::sailcomment:drivers[type=anchor,indent=0]
sail::retirement[type=type]

include::sailcomment:retire[type=function,indent=0]
sail::retire[type=function]

include::sailcomment:run_instruction[type=val,indent=0]
sail::run_instruction[type=val]

sail::run_instruction[type=function]

include::sailcomment:step[type=val,indent=0]
sail::step[type=val]

sail::step[type=function]

include::sailcomment:reset[type=val,indent=0]
sail::reset[type=function]

include::sailcomment:section_assembly_syntax[type=anchor,indent=0]

include::sailcomment:syntax[type=anchor,indent=0]

include::sailcomment:reg_name[type=val,indent=0]
sail::reg_name[type=val]

include::sailcomment:unsigned_dec_8[type=val,indent=0]
sail::unsigned_dec_8[type=val]

include::sailcomment:signed_dec_5[type=val,indent=0]
sail::signed_dec_5[type=val]

sail::signed_dec_8[type=val]

sail::signed_dec_11[type=val]

include::sailcomment:assembly_syntax[type=val,indent=0]
sail::assembly_syntax[type=val]

sail::assembly[type=val]
sail::assembly[type=function]
