"""Stubs for `src.simulation.cpu` from the TARA Studio wheel (taracpu 1.2.2)."""

type DecodedField = int | str

OP: dict[str, int]
OP_NAME: dict[int, str]
FMT: dict[str, str]

def sext(val: int, bits: int) -> int: ...

class TaraCPU:
    MEM_SIZE: int
    reg: list[int]
    pc: int
    mem: bytearray
    halted: bool
    error: str | None
    cycle_count: int
    instr_count: int
    last_instr: dict[str, DecodedField] | None

    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def load_program(self, words: list[int], start: int = 0) -> None: ...
    def read_word(self, addr: int) -> int: ...
    def write_word(self, addr: int, val: int) -> None: ...
    def read_byte(self, addr: int) -> int: ...
    def write_byte(self, addr: int, val: int) -> None: ...
    def decode(self, word: int) -> dict[str, DecodedField]: ...
    def step(self, record_history: bool = True) -> bool: ...
